# Static Routes
flight_home:
    pattern: /
    defaults: { _controller: FlightBundle:Default:index }

static:
    path: /{slug}
    defaults: { _controller: FlightBundle:Static:index, slug: slug}

# Flight Routes
flight_index:
    pattern: /{_locale}/home
    defaults: { _controller: FlightBundle:Default:index }
    requirements:
        _locale: en|fr