parameters:
#    flight.example.class: AirAtlantique\FlightBundle\Example

services:
     utilFlight:
         class: AirAtlantique\GeneratorBundle\Service\UtilFlight
#    flight.example:
#        class: %flight.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
