parameters:
#    flight.example.class: AirAtlantique\FlightBundle\Example

services:
#    flight.example:
#        class: %flight.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
