user:
    pattern: /
    defaults: {_controller: UserBundle:User:index}

user_new:
    pattern: /new
    defaults: {_controller: UserBundle:User:new}

user_create:
    pattern: /create
    defaults: {_controller: UserBundle:User:create}
    requirements:
        _method: POST

user_show:
    pattern: /show/{id}
    defaults: {_controller: UserBundle:User:show}

user_edit:
    pattern: /edit
    defaults: {_controller: UserBundle:User:edit}

user_delete:
    pattern: /delete/{id}
    defaults: {_controller: UserBundle:User:delete}
