user:
    pattern: /
    defaults: {_controller: UserBundle:Security:index}

user_new:
    pattern: /new
    defaults: {_controller: UserBundle:Security:new}

user_create:
    pattern: /create
    defaults: {_controller: UserBundle:Security:create}
    requirements:
        _method: POST

user_show:
    pattern: /show/{id}
    defaults: {_controller: UserBundle:Security:show}

user_edit:
    pattern: /edit
    defaults: {_controller: UserBundle:Security:edit}

user_delete:
    pattern: /delete/{id}
    defaults: {_controller: UserBundle:Security:delete}

user_login:
    pattern: /login
    defaults: {_controller: UserBundle:Security:login}
