parameters:
  airatlantique_user.authentication.handler.login_success_handler.class: AirAtlantique\UserBundle\Authentication\Handler\LoginSuccessHandler
  airatlantique_user.authentication.handler.login_failure_handler.class: AirAtlantique\UserBundle\Authentication\Handler\LoginFailureHandler
  airatlantique_user.authentication.handler.logout_success_handler.class: AirAtlantique\UserBundle\Authentication\Handler\LogoutSuccessHandler

services:
    airatlantique_user.registration.form.type:
        class: AirAtlantique\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: airatlantique_user_registration }

    airatlantique_user.authentication.handler.login_success_handler:
        class: %airatlantique_user.authentication.handler.login_success_handler.class%
        arguments:
            - @router
        tags:
            - { name: 'monolog.logger', channel: 'security' }

    airatlantique_user.authentication.handler.login_failure_handler:
        class: %airatlantique_user.authentication.handler.login_failure_handler.class%
        arguments:
            - @router
        tags:
            - { name: 'monolog.logger', channel: 'security' }

    airatlantique_user.authentication.handler.logout_success_handler:
        class: %airatlantique_user.authentication.handler.logout_success_handler.class%
        arguments:
            - @router
        tags:
            - { name: 'monolog.logger', channel: 'security' }
