<?php

namespace AirAtlantique\CartBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SeatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeatRepository extends EntityRepository
{
  // public function getSeatAvailable($flightList){
  //   foreach ($flight as $key => $flightList) {
  //     if($flight.isAvailable()){
  //       return
  //     }
  //     return;
  //   }
  // }

  // public function isAvailable($flight){

  //   if ($flight->planeId->first > 0){

  //   }
  //   if ($flight->planeId->business > 0){

  //   } 
  //   if ($flight->planeId->premiumEconomy > 0){

  //   }
  //   if ($flight->planeId->economy > 0){

  //   }     
  // }
}
