jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        AirAtlantique\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id:  fos_user.user_provider.username_email

    firewalls:
        main:
            pattern:  ^/
            anonymous:  true
            provider:  fos_userbundle
            form_login:
                provider:  fos_userbundle
                remember_me:  true
                use_forward:  false
                success_handler: airatlantique_user.authentication.handler.login_success_handler
                failure_handler: airatlantique_user.authentication.handler.login_failure_handler
                check_path: fos_user_security_check
                login_path: fos_user_security_login
                csrf_provider: form.csrf_provider

            logout:
                path:  fos_user_security_logout
                target: /fr/home
            remember_me:
                key:  %secret%

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security:  false

        login:
            pattern:  ^/(login$|register|resetting)
            anonymous:  true

        # secured_area:
        #     pattern:    ^/demo/secured/
        #     form_login:
        #         check_path: _security_check
        #         login_path: _demo_login
        #     logout:
        #         path:   _demo_logout
        #         target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    #access_control:
    #    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
