parameters:
   # doctrine.orm.entity_manager: Symfony\Bundle\DoctrineBundle\Registry

services:
    utilFlight:
        class: AirAtlantique\GeneratorBundle\Service\UtilFlight
        arguments: ["@kernel", '@doctrine.orm.entity_manager']
#    service.example:
#        class: %service.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    utilUser:
        class: AirAtlantique\GeneratorBundle\Service\UtilUser
        arguments: ["@kernel", '@doctrine.orm.entity_manager',"@security.encoder_factory"]