<?php

namespace AirAtlantique\PaymentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlaneTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaneTicketRepository extends EntityRepository
{
}
