<?php

namespace AirAtlantique\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BilletAvionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BilletAvionRepository extends EntityRepository
{
}
