<?php

namespace AirAtlantique\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MembershiCardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembershipCardRepository extends EntityRepository
{
}
