<?php

namespace AirAtlantique\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
  public function deleteAll()
    {
      $query = $this->createQueryBuilder('deleteAll');

      $query->delete();

      $query->getQuery()->execute();
    }
}
