parameters:
#    mailing.example.class: AirAtlantique\MailingBundle\Example

services:
#    mailing.example:
#        class: %mailing.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
